### ISSUE TITLE
Show balance over time per txn

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#113]
Building upon #106, is it possible to show the balance in the address after each transaction?

**Comment by Senyoret1** [comment]
At this time it is possible, but if the paging functionality is implemented (https://github.com/skycoin/skycoin-explorer/issues/89), then it depends. If paging is applied, it would be possible if the node's api returns the balance (I'm not sure what implications it would have on performance of the node), If the paging is made directly on explorer.go (to include the balance in case it is more efficient or convenient than doing it in the node's api.), and also if the explorer makes some somewhat inefficient requests, for example:

If the user requests the first page, the address balance after each transaction is calculated by adding or subtracting to the available balance the number of coins going in or out during the transaction, sequentially. If the user then requests page 3, the explorer asks the server for all the transactions on page 2 and 3, in order to continue making the additions sequentially. The inefficiency is having to request the data on page 2. If the user then asks for page 99 (out of a total of 100), the explorer requests the transactions of page 100 and 99, and make the additions in reverse order, to be more efficient than request from 4 to 99.

If any of these options seems acceptable to you, I can make the change now and the necessary modifications after pagination is implemented.

**Comment by gz-c** [comment]
Something like this belongs in the API response data?

**Comment by Senyoret1** [comment]
I guess it depends on what the API objectives are and the design considerations.

As the end point is /explorer/address, I would say yes. As it is an end point specifically made for the explorer (I guess it's like that because it starts with /explorer), it should contain all the information needed for making the operation inf the explorer as efficient as possible. However, you may want to make the api points as generic as possible, so that the api is more flexible. In that case, an additional option may be to create a new api endpoint to check the balance of the address after a specific transaction.

You are the one who has the general vision of the project, that's why I almost always try to give several options instead of choosing one directly.

In any case, requesting the data from the intermediate pages from the explorer (the last alternative in my previous message) could also be a temporary solution while deciding what is most convenient.

**Comment by gz-c** [comment]
We can extend the endpoint to include all necessary data for the explorer to render

**Comment by Senyoret1** [comment]
I made the changes, as the screen still has no paging: https://github.com/skycoin/skycoin-explorer/pull/115
