### ISSUE TITLE
Transaction detail page information improvements

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#12]
explorer page: http://127.0.0.1:8001/app/transaction/7d94d6e5c0825b590337406e551c2c20815589fb8ce7ae9521f944ca11d9ecee

skycoin data: http://127.0.0.1:6420/transaction?txid=7d94d6e5c0825b590337406e551c2c20815589fb8ce7ae9521f944ca11d9ecee

Duplicate inputs on the left side.  They are also the wrong inputs.

The transaction detail page also makes uxout requests for each output but does nothing with the information.

**Comment by xano8437** [comment]
Currently the code uses the uxout requests to get the input addresses of the inputs, which is why it shows a different response than http://127.0.0.1:6420/transaction?txid=7d94d6e5c0825b590337406e551c2c20815589fb8ce7ae9521f944ca11d9ecee

Do we want to show the inputs of the transaction call instead or should we keep showing the inputs from the uxout requests? If so, should I remove duplicates?

**Comment by gz-c** [comment]
hm either remove duplicates,
or show the number of coins and uxid per input address

**Comment by gz-c** [comment]
maybe get rid of the coins column, which are output coins, and display the same coins,hours,uxid information per input and output address

**Comment by samuelvisscher** [comment]
This appears to be resolved
