### ISSUE TITLE
Add begin & end variables to /api/address

### ISSUE THREAD

**Issue by samuelvisscher** [skycoin/skycoin-explorer#89]
When querying:

http://localhost:4200/api/address?address=2GgFvqoyk9RjwVzj8tqfcXVXB4orBwoc9qv

There's a long delay, because it has made over 4000 transactions. Let's reduce this overhead by adding begin & end handling in the explorer.go script.

**Comment by Senyoret1** [comment]
Putting these parameters in explorer.go would help to improve the response times, because the slowness seems to be mainly due to the download of the data and the creation of the large number of elements in the DOM. However, the node's api does not have these parameters, so each local request made by explorer.go would still retrieve from the node all the transactions, which leaves room for improvements.

To make the process more efficient, it would be necessary to change /explorer/address (node api), what is also proposed in https://github.com/skycoin/skycoin-explorer/issues/90. Possibly the function could be modified to adapt it to the requirements of https://github.com/skycoin/skycoin-explorer/issues/90 and this issue, which would allow to apply efficient solutions in the explorer. May be it would be good to make a decision regarding this before starting.

**Comment by gz-c** [comment]
The explorer only proxies requests from the skycoin node.  API changes need to be made in the skycoin node first

**Comment by gz-c** [comment]
Can you make issues for these in skycoin/skycoin and reference the issues here?

**Comment by gz-c** [comment]
Edit: made issues for this and #90 and backlinked them

**Comment by gz-c** [comment]
Issue moved to https://github.com/skycoin/skycoin/issues/867
